/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models-3d/Lung.glb --types --transform 
Files: public/models-3d/Lung.glb [12.89MB] >  \pul-lab\Lung-transformed.glb [4.98MB] (61%)
*/

import { JSX, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Group  } from "three";
import { GLTFResult } from '../interfaces/Lung';
import useStoreLung from '../store/useStoreLung';

export default function LungModel(props: JSX.IntrinsicElements['group']) {
  const group = useRef<Group>(null)
  const {  isActiveAnimation} = useStoreLung()
  const { nodes, materials, animations } = useGLTF( "/models-3d/pneumonia/Lung-transformed.glb") as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions.BeatingLung && actions.BeatingDiaphragm && isActiveAnimation) {
      actions.BeatingLung.play();
      actions.BeatingDiaphragm?.play()
    }
  }, [actions, isActiveAnimation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group  name="Scene">
        <group  name="Trachea"  >
          <mesh castShadow  name="Trachea_1"   geometry={nodes.Trachea_1.geometry} material={materials.TracheaArytenoidMaterial} />
          <mesh castShadow  name="Trachea_2" geometry={nodes.Trachea_2.geometry} material={materials.TracheaMaterial} />
          <mesh castShadow  name="Trachea_3" geometry={nodes.Trachea_3.geometry} material={materials.TracheaCricoidMaterial} />
          <mesh castShadow  name="Trachea_4" geometry={nodes.Trachea_4.geometry} material={materials.TracheaEpiglosttisMaterial} />
          <mesh castShadow  name="Trachea_5" geometry={nodes.Trachea_5.geometry} material={materials.TracheaHyoidMaterial} />
          <mesh castShadow  name="Trachea_6" geometry={nodes.Trachea_6.geometry} material={materials.TracheaLarynxMaterial} />
          <mesh castShadow  name="Trachea_7" geometry={nodes.Trachea_7.geometry} material={materials.TracheaMedianMaterial} />
          <mesh castShadow  name="Trachea_8" geometry={nodes.Trachea_8.geometry} material={materials.TracheaThyrocricoidMaterial} />
          <mesh castShadow  name="Trachea_9" geometry={nodes.Trachea_9.geometry} material={materials.TracheaThyrohyoidMaterial} />
          <mesh castShadow  name="Trachea_10" geometry={nodes.Trachea_10.geometry} material={materials.TracheaThyroidMaterial} />
          <mesh castShadow  name="Trachea_11" geometry={nodes.Trachea_11.geometry} material={materials.TracheaVocalMaterial} />
        </group>
        <group name="Lung">
          <mesh castShadow name="Lung_1" geometry={nodes.Lung_1.geometry} material={materials.LungRightMaterial} morphTargetDictionary={nodes.Lung_1.morphTargetDictionary} morphTargetInfluences={nodes.Lung_1.morphTargetInfluences} />
          <mesh castShadow name="Lung_2" geometry={nodes.Lung_2.geometry} material={materials.LungPulmonaryVeinsMaterial} morphTargetDictionary={nodes.Lung_2.morphTargetDictionary} morphTargetInfluences={nodes.Lung_2.morphTargetInfluences} />
          <mesh castShadow name="Lung_3" geometry={nodes.Lung_3.geometry} material={materials.LungPulmonaryArteriesMaterial} morphTargetDictionary={nodes.Lung_3.morphTargetDictionary} morphTargetInfluences={nodes.Lung_3.morphTargetInfluences} />
          <mesh castShadow name="Lung_4" geometry={nodes.Lung_4.geometry} material={materials.LungLeftMaterial} morphTargetDictionary={nodes.Lung_4.morphTargetDictionary} morphTargetInfluences={nodes.Lung_4.morphTargetInfluences} />
        </group>
        <mesh castShadow name="Diaphragm" geometry={nodes.Diaphragm.geometry} material={materials.DiaphragmMaterial} morphTargetDictionary={nodes.Diaphragm.morphTargetDictionary} morphTargetInfluences={nodes.Diaphragm.morphTargetInfluences} />
      </group>
    </group>
  )
}

useGLTF.preload( "/models-3d/pneumonia/Lung-transformed.glb")
