/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models-3d/tuberculosis/lung-tuberculosis.glb --types 
*/

//import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Mesh, MeshStandardMaterial } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    Lung: Mesh
  }
  materials: {
    Material_0: MeshStandardMaterial
  }
}

export function LungTuberculosisModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models-3d/tuberculosis/lung-tuberculosis.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Lung.geometry} material={materials.Material_0} />
    </group>
  )
}

useGLTF.preload('/models-3d/tuberculosis/lung-tuberculosis.glb')
