/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Lung: THREE.Mesh
  }
  materials: {
    LungMaterial: THREE.MeshStandardMaterial
  }
}

export function LungTuberculosisModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models-3d/tuberculosis/Lung-tuberculosis.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lung.geometry}
        material={materials.LungMaterial}
      />
    </group>
  )
}

useGLTF.preload('/models-3d/tuberculosis/Lung-tuberculosis.glb')
